---
name: Test `tailscale-qemu-runner-action`
on:
  pull_request:
    branches:
      - main
jobs:
  create-runner:
    name: Create self-hosted runner VM
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      max-parallel: 1
      matrix:
        runner-name: [test]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.2.2
      - name: Create runner
        uses: ./
        with:
          gh-api-token: ${{ secrets.GH_API_TOKEN }}
          gha-runner-apt-mirror: http://au.archive.ubuntu.com/ubuntu/
          gha-runner-cpus: 2
          gha-runner-mem: 1G
          gha-runner-tz: Australia/Brisbane
          ssh-host: 100.102.37.118
          ssh-user: matthew
          ts-oauth-client-id: ${{ secrets.TS_OAUTH_CLIENT_ID }}
          ts-oauth-secret: ${{ secrets.TS_OAUTH_SECRET }}
          ts-tag: ci
  test-runner:
    name: Test self-hosted runner
    runs-on: self-hosted
    strategy:
      fail-fast: false
      max-parallel: 1
      matrix:
        runner-name: [test]
    steps:
      - name: Tell the time
        run: |
          set -eu
          echo "Testing runner..."
          date
          echo "Test completed successfully!"
